### ISSUE TITLE
Several issues with 1.5.0

### ISSUE THREAD

**Issue by Qwinn1** [joaquimguimaraes/farmr#62]
Having several issues:

1)  The standalone farmr-linux-x86_64.tar.gz appears to have a config file only for XCH.  No config files for any forks found.  Pretty sure it used to have some.

2)  I can change the name in my config files, but it still keeps returning only the names "Farmer" and "Harvester" in the output.  It's also not showing my cold wallet balance properly.  It seems like it's not reading the config-xch.json file at all.  This also affects my Flax install.

3)  In trying to fix the name issue in my second issue on Windows, I opened the files in the "cache" folder and noted that the first line was still returning a path to the bin file for version 1.1.7.  I am on 1.2.0 on all my machines.  When I tried deleting those cache files and restarting, the path in the newly generated cache-xch.json "binPath" now comes up blank.  Not sure if that's a *problem*, but thought it might help diagnose.  Aside from the "Name" thing, though, it appears to be working correctly (I do see a display of the Windows Drives).

5)  Can you confirm that updating versions will require removing the devices from Farmr and readding them with a new key?  Because it seems like that is in fact a requirement, might want to make that explicit in update instructions.

Thanks again for all your work!

**Comment by Qwinn1** [comment]
Sorry!  The version issue with my Ubuntu attempts were my fault.  I was apparently still grabbing the previous version (I followed the link from a previous issue).  My bad.  I have successfully gotten the Ubuntu card to show up as 1.5.0 now.

However, the "Name" functionality in the config appears to be broken for Ubuntu as well as Windows, can't change the name for anything.  

I've edited my first post to remove the reports that were just my stupidity, and left what's still pertinent.

**Comment by joaquimguimaraes** [comment]
Hey, I've made some changes in 1.5.0 to make it easier to configure for most people.
As long as "Online Config" is not set to false in your blockchain file, it will only be configurable from farmr.net
There's a settings button in farmr.net for opening the settings menu

I don't think binPath would be an issue. It works slightly differently now.

Updating versions should not require removing devices and readding them with a new key if you preserve id.json file.

**Comment by joaquimguimaraes** [comment]
Regarding to question number 1, the .gz files only come with config-xch.json (and always been like that, you can check previous releases). The reason you don't see other files after you start farmr is that it doesn't need to generate config files for other forks now that it defaults to online configuration.

**Comment by Qwinn1** [comment]
Hey!  Thanks for the quick response.

My blockchain files did say "Online Config": true, but I still did not get options online.  All I get when clicking the "Settings" gear are the dashboard color scheme and the currency.

Good news is that setting it to false DID make my old config file work again, so I'm operational again.

Thanks for the answer on the id.json file.  I recommend in the update section of your documentation to specify which files should ideally be transferred from the previous install, like id.json and the config files.  I blew away my Windows config unfortunately before realizing I should've backed it up before overwriting.

**Comment by joaquimguimaraes** [comment]
You need to have a specific device selected to edit its config. It wont work if the whole farm is selected

**Comment by Qwinn1** [comment]
Yah, I figured that out, thanks.  This is probably harder for me than for most people since I have to use the whole standalone version thing to get simultaneous farmers and harvesters.  I think I'm finally beginning to work out how to get it all sorted.  I think I'm getting there with Chia, but still having issues with Flax.  Will let you know how it goes.

**Comment by Qwinn1** [comment]
Think I got it all sorted.  Phew!  One note I'll throw out is that my Flax Harvester setup on a server that was also running a Chia Farmer (so two separate installs) simply *would not* add to the display while I only had a config-xfx.json in the config directory, even though I only had an active xfx.json in the blockchain directory, no xch.json.  The only way I was able to get my flax harvester to add was by putting a config-xch.json in the config directory... which seemed odd since the contents of the file were being ignored regardless.

As a suggestion, I think it would be significantly less difficult for existing users that are comfortable with config files (mostly Linux users, I know) to transition to this version if the online configuration were to initially read whatever values are in any existing config-xxx.json file.  You could -then- switch to full online configuration and ignore the config file from then on, but as it is, all your settings go clean slate when you update to this version, which is a bit confusing if you didn't expect it.

**Comment by Qwinn1** [comment]
Everything seems to be working well now, except the total count of drives is off on both my Flax and Chia Farm entries.  The farmer and individual harvesters all report the correct amount of drives, and even the Farm entry lists the correct number of drives in the listing at the bottom of the page, but the total count on the card is off.  The correct number of drives is 37 for both chia and flax for me, but my Chia Farm entry says 48 and my Flax entry says 47.  Note that I do have one system with 11 drives and another with 10, so it seems like each of them is double counting a server's count, just not the same one.  

If it matters, under the drive list Devices column, I have several device names duplicated because my Linux servers are often assigned the same name (example: /dev/sde exists on all 3 of my Linux servers).  That's fine, I don't need it to make a distinction for me, but I'm wondering if it might not be confusing whatever you're using to add them up.

**Comment by joaquimguimaraes** [comment]
I think the issue with number of drives is related to mounted paths in windows. 

And yes I plan to add a column that shows which device they’re from

**Comment by Qwinn1** [comment]
Cool.  FYI, the "Last Updated X Minutes Ago" cards didn't update for me all night.  Woke up to them saying over 360 minutes each.  Refreshing with the button on the page didn't fix it, only closing the tab and reopening it worked.  Then they read 8-20 minutes as expected.

**Comment by PiSCaRGoT** [comment]
I have the same problem. I initially thought it was the difference from using local and online config. But I realize after a while, it does not auto refresh anymore regardless of local or online config. 

Until I ctrl-f5 or close tab & reopen, then its ok for a while. But will happen again.

**Comment by joaquimguimaraes** [comment]
Interesting. I’ll have to see if this is related to cloudflare caching.

**Comment by Qwinn1** [comment]
"I think the issue with number of drives is related to mounted paths in windows."

I don't think this is the case.  I went and added two drives to one of my Ubuntu servers, and oddly, the count went from 48 to 51 on my one Ubuntu farm and 47 to 50 on my other Ubuntu farm.  Why they increased by 3 instead of 2, I have no idea.  Then, when I added 2 drives to my other Ubuntu server (this one harvester for both flax and chia), both farms went to 53.  No changes to my Windows harvester in either case.

Another issue:  I hit XFX twice today, one about 4 hours ago and the other 3 hours ago, but the cards for my Flax Farm and Farmer the ETW cards are still reporting "Started farming X days ago" instead of "Last block X days ago", as if I've never hit.  As reported previously, on both flax and chia all the harvesters say "Last block 0 days ago".  My chia Farm and Farmer are correctly reporting the last time I won a chia block on that card.

I will note that my chia farm reports on a cold wallet, whereas my flax farm is still a hot wallet (I plan on fixing that soon).

**Comment by joaquimguimaraes** [comment]
Yes, there was an issue with "hot wallet" efforts which appeared in v1.5.0 
This has been addressed and fixed in v1.5.0.2

I will leave this thread open so we can spot/fix other issues mentioned in it

**Comment by Qwinn1** [comment]
Can confirm my flax hot wallet balance, and the "last block" info on the ETW card, both fixed in v1.5.0.2.  Thanks!

Outstanding issues:  

1)  Total count of drives still misreported on Drives Card in Farm tab (correct everywhere else, including listing of Drives at bottom of Farm tab).

2)  Refresh on Last Updated card.... will report back on this one, can't confirm still happening in v1.5.0.2 as it takes a while to note updates have stopped.

3)  Some interesting info on the other issue where I requested that last block won on ETW card be specific to harvester.  Will update that thread.

**Comment by Qwinn1** [comment]
Just confirming, yep, at least the Last Updated card is still not refreshing on 1.5.0.2 until the entire browser tab is refreshed.

**Comment by Qwinn1** [comment]
Hullo.  Wanted to report that earlier tonight I rebooted all of my machines, and even after that my farms were still showing 53 drives... but after a few hours, they are now correctly displaying 41 drives.  Dunno if you tried to do something on the front end to fix it, but whatever happened, the Drives card seems to be working now.  If it reverts to being incorrect I'll let you know.

**Comment by joaquimguimaraes** [comment]
Yes, I just updated it with a couple of fixes.
Namely, fixed drive counting and those refresh issues.

**Comment by Qwinn1** [comment]
Awesome, thank you!  All seems to be working great now.  And I did figure out a card layout I can be content with for both farmers and harvesters.  So far as I'm concerned, my enhancement request for showing Last Proof Found by harvester is the only request I've got left.

Oooh, wait, I did think of one other possible enhancement request (if you like it let me know and I'll set it up as a separate issue).  Your Version card currently shows the version number for Farmr.  Would it be possible to add the Chia/Flax version # installed on that harvester/farmer as well?  I honestly have no idea how to actually query for that myself - even in the Gui, selecting "About Chia" doesn't display the version #.  With all the 1.2.0 / 1.2.1 and more versions coming out rapidly and having to update one by one, it'd be handy to have Farmr confirm the update worked, if you know how to query for it.

**Comment by joaquimguimaraes** [comment]
That's a nice suggestion and would be very easy to implement.

**Comment by Qwinn1** [comment]
Awesome, I'll set it up as a separate issue, thank you!

**Comment by Qwinn1** [comment]
Minor issue report:  On my Windows harvester, in the open command box that you have to leave running for farmr to work, it keeps sending "Do NOT close this window." over and over again,  This happens twice as soon as I fire farmr up (I presume because I'm sending harvester reports for both chia and flax), and then twice again every so often with each data send.  Repeated "Do NOT close this window."s will eventually scroll the new menu options off the screen completely.  It doesn't behave this way in Ubuntu - there, it just stays on the new menu.

**Comment by joaquimguimaraes** [comment]
Most of these issues were fixed
